### ISSUE TITLE
Error when installing the plugin

### ISSUE THREAD

**Issue by SylvanoTombo** [SplashSync/Sylius-Bundle#7]
[InvalidArgumentException]                                                                                                                                                         
  Could not find a version of package splash/sylius-bundle matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by BadPixxel** [comment]
Hi Sylvano,

You should add splash/phpcore:dev-master splash/php-bundle:dev-master to your composer requires.

Best regards,
