### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by SylvanoTombo** [SplashSync/Sylius-Bundle#8]
error:  Trait 'Splash\Tests\Tools\Traits\SuccessfulTestPHP7' not found in /app/vendor/splash/sylius-bundle/tests/KernelTestCase.php on line 31

**Comment by BadPixxel** [comment]
Hi,

Yes this line should now be commented. 
Can you tell us which version of Silius you are using? We will update our module soon.

Best regards,
